name: Deploy

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest 

    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: 85.208.51.17   
          username: root        
          key: ${{ secrets.SSH_PRIVATE_KEY }}  # Store your SSH key in GitHub Secrets
          script: |
            cd ~/fastapi-book-project
            git pull origin main
            source venv/bin/activate
            pip install -r requirements.txt
            systemctl restart fastapi-app  
            systemctl restart nginx        
