name: CI Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.8"  # Ensure this matches your local Python version

      - name: Check Python Version
        run: python --version  # Verify Python version in the CI environment

      - name: Install dependencies
        run: |
          python -m venv venv
          . venv/bin/activate
          pip install --no-cache-dir --upgrade-strategy only-if-needed -r requirements.txt

      - name: Run Tests
        run: |
          . venv/bin/activate
          pytest
